### ISSUE TITLE
Have a section of issues for each project

### ISSUE THREAD

**Issue by aswinzz** [opencode18/OpenCode-Collaborative#131]
We would like to have a section for all open issues under opecode .
This issue requires usage of github api

**Comment by GOVINDDIXIT** [comment]
i will do it

**Comment by aswinzz** [comment]
@GOVINDDIXIT ou have been assigned

**Comment by anshumanv** [comment]
Can multiple people collaborate on an issue or only one can do it once it is assigned? Also is there a time span within which it is to be completed? @aswinzz

**Comment by aswinzz** [comment]
Only one person can work on an issue and if there is no response from the assignee we will float the issue to others

**Comment by aswinzz** [comment]
@GOVINDDIXIT  status?

**Comment by lilly452** [comment]
To effectively manage project issues, create a dedicated section for each project that includes the following key elements:

1. **Issue Title**: A brief, descriptive title for each issue.
2. **Issue Description**: A detailed description outlining the problem, its impact, and any relevant context.
3. **Priority Level**: Assign a priority (e.g., low, medium, high) to help with task management and resource allocation.
4. **Status**: Track the current status of the issue (e.g., open, in progress, resolved).
5. **Assigned To**: Specify the team member responsible for resolving the issue.
6. **Date Reported**: Record the date when the (https://cotonmode.co.uk/collections/bath-mats) issue was first reported.
7. **Target Resolution Date**: Set a deadline for resolving the issue to ensure timely action.
8. **Comments/Updates**: Provide a section for team members to add comments and updates on the progress of the issue.
9. **Attachments**: Include any relevant files or screenshots that can aid in understanding and resolving the issue.
10. **Resolution Details**: Once resolved, document how the issue was addressed and any steps taken to prevent future occurrences.
