### ISSUE TITLE
Implement lazy loading 

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/OpenCode-Collaborative#310]

**Comment by Ace-Bansal** [comment]
can i work on this?

**Comment by gauthamzz** [comment]
@Ace-Bansal 👍 go ahead

**Comment by Ace-Bansal** [comment]
I used the Lazy Load jQuery plugin but that's working only on the OpenCode logo and the images in the footer but not on the participants' and mentors' images (maybe because these images are being fetched from a JSON file).
So instead I tried lazy loading the divs that contain the cards of mentors and participants. However I'm not quite sure if it's working. It's not showing any error in the console though. I used the method given in the first answer [here](https://stackoverflow.com/questions/8192651/load-lazy-loading-a-div-whenever-the-div-gets-visible-for-the-first-time).  
Would you please guide me here?

**Comment by Ace-Bansal** [comment]
@gauthamzz

**Comment by Anupam-dagar** [comment]
@Ace-Bansal come over to zulip

**Comment by Ace-Bansal** [comment]
can i be unassigned from this issue? I tried a lot but just couldn't implement it.

**Comment by Anupam-dagar** [comment]
@falconis assigned

**Comment by falconis** [comment]
Pls reassign. Couldn't implement it.

**Comment by Anupam-dagar** [comment]
This issue is open to take

**Comment by ashish4321** [comment]
can i work on this?

**Comment by aswinzz** [comment]
@ashish4321  status?

**Comment by ashish4321** [comment]
pls reassign it..i could not implement lazy loading

**Comment by aswinzz** [comment]
Open for others!
