### ISSUE TITLE
Add All the mentors 

### ISSUE THREAD

**Issue by aswinzz** [opencode18/OpenCode-Collaborative#8]

**Comment by falconis** [comment]
I would like to work on this.

**Comment by Anupam-dagar** [comment]
@falconis sure

**Comment by falconis** [comment]
So how do I get the details of the mentors? Especially their social media ids?

**Comment by aswinzz** [comment]
update only the names and image.Take the mentors from projects page and the images from github account.

**Comment by falconis** [comment]
Alright.

**Comment by aswinzz** [comment]
@falconis  what is the status?

**Comment by falconis** [comment]
I'll complete it by 6pm. Will it be ok?

**Comment by Panda2498** [comment]
Are their any other mentors to be added other than the two that are already added?

**Comment by Anupam-dagar** [comment]
@Panda2498 @falconis is currently working on this.You may work on other issue, comment on the one you want to work

**Comment by falconis** [comment]
So I added the mentor details in the json file and the images in the mentor file. But there is no change in the website...

**Comment by Panda2498** [comment]
I wasn't able to upload the images, it wasn't giving me the permission to
do so, so for now I just mentioned the github image url of the mentors. I
will change them to images when I get the permission to do so.

On Jan 10, 2018 3:57 PM, "Vishal Pani" <notifications@github.com> wrote:

So I added the mentor details in the json file and the images in the mentor
file. But there is no change in the website...

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/opencode18/OpenCode-Collaborative/issues/8#issuecomment-356561468>,
or mute the thread

**Comment by Panda2498** [comment]
Okay! I didn't know that we have to comment before resolving an issue.

**Comment by gauthamzz** [comment]
Close issues as they go.
